In [ ]:
1)

import pandas as pd

data = [4, 8, 15, 16, 23, 42]
series = pd.Series(data)
print(series)

In [ ]:
2)

import pandas as pd

my_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
my_series = pd.Series(my_list)

print(my_series)

In [ ]:
3)

import pandas as pd

data = {
    'Name': ['Alice', 'Bob', 'Claire'],
    'Age': [25, 30, 27],
    'Gender': ['Female', 'Male', 'Female']
}

df = pd.DataFrame(data)
print(df)

In [ ]:
4)

import pandas as pd

# create a dictionary of data
data = {
    'Name': ['Alice', 'Bob', 'Claire'],
    'Age': [25, 30, 27],
    'Gender': ['Female', 'Male', 'Female']
}

# create a DataFrame from the dictionary
df = pd.DataFrame(data)

# create a Series from the 'Age' column of the DataFrame
age_series = df['Age']

print(df)
print(age_series)


In the above example, we created a dictionary of data containing three columns: Name, Age, and Gender. We then used this dictionary to create a DataFrame using the pd.DataFrame function.

In [ ]:
5)

There are many functions available in Pandas for data manipulation in a DataFrame, but some of the most common ones are:

head() and tail(): these functions allow you to view the first or last n rows of your DataFrame, respectively. You might use these functions to get a quick sense of the data you're working with.
Example:

python
Copy code
import pandas as pd

df = pd.read_csv('mydata.csv')
print(df.head())
describe(): this function gives you a summary of various statistics for each numerical column in your DataFrame, including count, mean, standard deviation, minimum, and maximum. You might use this function to get an overview of your data's distribution.
Example:

python
Copy code
import pandas as pd

df = pd.read_csv('mydata.csv')
print(df.describe())
groupby(): this function allows you to group your DataFrame by one or more columns and then perform operations on each group. You might use this function to calculate summary statistics for different groups in your data.
Example:

python
Copy code
import pandas as pd

df = pd.read_csv('mydata.csv')
grouped = df.groupby('Category')
print(grouped.mean())
drop(): this function allows you to drop one or more columns or rows from your DataFrame. You might use this function to remove columns that you don't need for analysis.
Example:

python
Copy code
import pandas as pd

df = pd.read_csv('mydata.csv')
df = df.drop('Column1', axis=1)
sort_values(): this function allows you to sort your DataFrame by one or more columns. You might use this function to order your data in a specific way.
Example:

python
Copy code
import pandas as pd

df = pd.read_csv('mydata.csv')
df = df.sort_values(by='Column1')
These are just a few examples of the many functions available in Pandas for manipulating data in a DataFrame.

In [ ]:
6)

Both Series and DataFrame are mutable in nature in Pandas. This means that you can modify the data contained in these data structures after they have been created. However, Panel is an immutable data structure in Pandas, which means that once created, its contents cannot be changed. Instead, a new panel object must be created with the desired changes. However, it is worth noting that the Panel data structure has been deprecated since version 0.25.0 of Pandas, and users are encouraged to use other data structures, such as MultiIndex DataFrames, in its place.

In [ ]:
7)

To create a DataFrame using multiple Series, we can pass a dictionary of Series to the pd.DataFrame() function. Each Series will become a column in the resulting DataFrame.

Here's an example:

bash
Copy code
import pandas as pd

# Create the Series
names = pd.Series(['Alice', 'Bob', 'Claire'])
ages = pd.Series([25, 30, 27])
genders = pd.Series(['Female', 'Male', 'Female'])

# Create the DataFrame
df = pd.DataFrame({'Name': names, 'Age': ages, 'Gender': genders})

# Print the DataFrame
print(df)
Output:

markdown
Copy code
     Name  Age  Gender
0   Alice   25  Female
1     Bob   30    Male
2  Claire   27  Female
In this example, we first create three Series: names, ages, and genders. Then, we pass them as a dictionary to the pd.DataFrame() function to create a DataFrame with three columns: Name, Age, and Gender. Each Series becomes a column in the resulting DataFrame.